services:
    postgres:
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
          interval: 10s
          timeout: 5s
          retries: 5

    app:
        build: .
        ports:
          - "8080:8080"
        env_file:
          - .env.dev
        environment:
          - DB_HOST=postgres
          - DB_PORT=5432
        depends_on:
          postgres:
            condition: service_healthy
        command: ["go", "run", "cmd/main.go"]