name: ci

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_API_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/microblog:latest
            ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/microblog:${{ github.run_number }}
            ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/microblog:${{ github.sha }}