name: ci

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
    branches:
      - pipeline-fix-4
  workflow_dispatch:

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_API_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/microblog:latest
            ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/microblog:${{ github.run_number }}
            ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/microblog:${{ github.sha }}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=My multi-arch image
      - name: Write image info to file
        run: |
          echo "IMAGE_TAG=${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/microblog:${{ github.sha }}" > image_info.txt
          echo "IMAGE_SHA=${{ github.sha }}" >> image_info.txt
      - name: Upload image info
        uses: actions/upload-artifact@v4
        with:
          name: image-info
          path: image_info.txt