name: terraform

on:
  workflow_run:
    workflows:
      - ci # Name of the workflow to depend on (from `ci.yaml`)
    types:
      - completed
 
env:
 TF_LOG: INFO
 SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
 SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_ACCESS }}
 BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
 
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }} # Only run if `ci.yaml` succeeded
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform Changes
        run: terraform plan

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve