name: terraform

on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed
  workflow_dispatch:
 
env:
 TF_VAR_organization_id: ${{ secrets.TF_VAR_organization_id }}
 AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
 SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
 SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
 BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
 TF_VAR_project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
 
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=${{ secrets.BUCKET_TF_STATE }}"

      - name: Plan Terraform Changes
        run: terraform plan

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve