on: [push, pull_request]
name: Tests

jobs:
  test:
    strategy:
      matrix:
        go-version: ['stable', 'oldstable']
        os: [ubuntu-latest] # Docker-in-Docker is only supported on Linux
    runs-on: ${{ matrix.os }}
    services:
      docker:
        image: docker:24.0.5-dind
        options: --privileged # Correctly set privileged mode here
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: Set up Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          docker version
      - name: Run Tests
        env:
          DOCKER_HOST: tcp://localhost:2375
        run: |
          go test ./... -v

  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: golang/govulncheck-action@v1

  gocritic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v3
      - run: |
          go install github.com/go-critic/go-critic/cmd/gocritic@latest
          gocritic check .