on: [push, pull_request]
name: Tests

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5-dind
        options: --privileged
        env:
          DOCKER_TLS_CERTDIR: ""
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: actions/checkout@v3
      - name: Verify Docker Installation
        run: docker version
      - name: Run Tests
        env:
          DOCKER_HOST: tcp://localhost:5432
        run: go test ./... -v

